# Generated by Django 2.1.4 on 2019-02-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribution',
            old_name='Timeslot',
            new_name='TimeSlot',
        ),
    ]
