#  Bep Marketplace ELE
#  Copyright (c) 2016-2022 Kolibri Solutions
#  License: See LICENSE file or https://github.com/KolibriSolutions/BepMarketplace/blob/master/LICENSE

# Generated by Django 2.1.4 on 2019-07-01 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20190225_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='Application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='students.Application'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='Proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='proposals.Proposal'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='TimeSlot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='timeline.TimeSlot'),
        ),
    ]
