# Generated by Django 3.2.11 on 2022-01-26 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0005_alter_distribution_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='Student',
            field=models.ForeignKey(limit_choices_to={'groups': None}, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to=settings.AUTH_USER_MODEL),
        ),
    ]
