bepmp:
  script:
    - redis-server &
    - REDIS_PID=$!
    - echo $REDIS_PID
    - virtualenv bepmarketplaceenv
    - . bepmarketplaceenv/bin/activate
    - python -V
    - pip -V
    - mkdir -p logging
    - mkdir -p tracking/telemetry/data/
    - pip install -r requirements.txt
    - pip install tblib
    - python dev_generate_secrets.py
    - touch startup.lock
    - python manage.py migrate --settings=BepMarketplace.settings_development
    - python manage.py test --settings=BepMarketplace.settings_development --parallel
    - kill $REDIS_PID || true