# Generated by Django 2.1.4 on 2019-04-29 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presentationset',
            options={'ordering': ['DateTime']},
        ),
    ]
