# Generated by Django 2.2 on 2019-06-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0002_auto_20190429_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationtimeslot',
            name='CustomType',
            field=models.IntegerField(choices=[(1, 'Assessment'), (2, 'Break'), (3, 'Cancelled')], default=0, null=True),
        ),
    ]
