# Generated by Django 3.0.6 on 2020-05-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0006_auto_20200529_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationtimeslot',
            name='CustomType',
            field=models.IntegerField(choices=[(0, 'Presentation'), (1, 'Assessment'), (2, 'Break'), (3, 'Cancelled')], default=0, null=True),
        ),
    ]
