#  Bep Marketplace ELE
#  Copyright (c) 2016-2022 Kolibri Solutions
#  License: See LICENSE file or https://github.com/KolibriSolutions/BepMarketplace/blob/master/LICENSE

# Generated by Django 3.0.8 on 2020-12-21 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0009_auto_20200609_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationset',
            name='AssessmentRoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessmentroom', to='presentations.Room'),
        ),
        migrations.AlterField(
            model_name='presentationset',
            name='PresentationRoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentationroom', to='presentations.Room'),
        ),
    ]
