# Generated by Django 2.1.5 on 2019-03-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timephase',
            options={'ordering': ['TimeSlot', 'Begin']},
        ),
        migrations.RenameField(
            model_name='timephase',
            old_name='Timeslot',
            new_name='TimeSlot',
        ),
    ]
