# Generated by Django 2.1.4 on 2019-02-15 13:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professionalskills', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffReponse',
            new_name='StaffResponse',
        ),
    ]
