# Generated by Django 2.1.4 on 2019-07-01 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionalskills', '0003_staffresponsefileaspect_staffresponsefileaspectresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfile',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='professionalskills.FileType'),
        ),
    ]
