# Generated by Django 2.1.4 on 2019-02-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitygroupadministration',
            name='Members',
        ),
        migrations.DeleteModel(
            name='CapacityGroupAdministration',
        ),
    ]
