# Generated by Django 3.2.11 on 2022-08-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20220112_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='Affiliation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='Studentnumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
