# Generated by Django 2.2 on 2019-05-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telemetrykey',
            old_name='Key',
            new_name='key',
        ),
    ]
