#  Bep Marketplace ELE
#  Copyright (c) 2016-2022 Kolibri Solutions
#  License: See LICENSE file or https://github.com/KolibriSolutions/BepMarketplace/blob/master/LICENSE

# Generated by Django 3.2.11 on 2022-01-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osirisdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessgrant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
