# Generated by Django 3.2.11 on 2022-01-25 10:39

from django.db import migrations, models
import django.db.models.deletion
import timeline.utils


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20220112_0940'),
        ('osirisdata', '0002_alter_accessgrant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsirisDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='')),
                ('TimeSlot', models.ForeignKey(default=timeline.utils.get_timeslot_id, on_delete=django.db.models.deletion.PROTECT, to='timeline.timeslot')),
            ],
        ),
    ]
